export const canonicalSkills: Record<string, string> = {
    // Variations mapped to Canonical form
    'k8s': 'Kubernetes',
    'kubernetes': 'Kubernetes',
    'kubernetes clusters': 'Kubernetes',
    'node': 'Node.js',
    'node js': 'Node.js',
    'nodejs': 'Node.js',
    'node.js': 'Node.js',
    'postgres': 'PostgreSQL',
    'postgresql': 'PostgreSQL',
    'react': 'React',
    'react js': 'React',
    'react.js': 'React',
    'reactjs': 'React',
    'aws': 'AWS',
    'amazon web services': 'AWS',
    'amazonwebservices': 'AWS',
    'gcp': 'Google Cloud Platform',
    'google cloud': 'Google Cloud Platform',
    'google cloud platform': 'Google Cloud Platform',
    'azure': 'Microsoft Azure',
    'microsoft azure': 'Microsoft Azure',
    'docker': 'Docker',
    'docker containers': 'Docker',
    'mongo': 'MongoDB',
    'mongodb': 'MongoDB',
    'js': 'JavaScript',
    'javascript': 'JavaScript',
    'ts': 'TypeScript',
    'typescript': 'TypeScript',
    'python': 'Python',
    'py': 'Python',
    'go': 'Go',
    'golang': 'Go',
    'rust': 'Rust',
    'java': 'Java',
    'c#': 'C#',
    'csharp': 'C#',
    'c++': 'C++',
    'cpp': 'C++',
    'ruby': 'Ruby',
    'rails': 'Ruby on Rails',
    'ruby on rails': 'Ruby on Rails',
    'php': 'PHP',
    'laravel': 'Laravel',
    'html': 'HTML',
    'html5': 'HTML',
    'css': 'CSS',
    'css3': 'CSS',
    'tailwind': 'Tailwind CSS',
    'tailwindcss': 'Tailwind CSS',
    'git': 'Git',
    'github': 'GitHub',
    'gitlab': 'GitLab',
    'bitbucket': 'Bitbucket',
    'ci/cd': 'CI/CD',
    'cicd': 'CI/CD',
    'linux': 'Linux',
    'unix': 'Linux', // Simplified
    'sql': 'SQL',
    'mysql': 'MySQL',
    'redis': 'Redis',
    'graphql': 'GraphQL',
    'rest': 'REST API',
    'rest api': 'REST API',
    'spring': 'Spring Boot',
    'spring boot': 'Spring Boot',
    'django': 'Django',
    'flask': 'Flask',
    'express': 'Express.js',
    'express.js': 'Express.js',
    'expressjs': 'Express.js',
    'next': 'Next.js',
    'next.js': 'Next.js',
    'nextjs': 'Next.js',
    'nuxt': 'Nuxt.js',
    'vue': 'Vue.js',
    'vue.js': 'Vue.js',
    'vuejs': 'Vue.js',
    'angular': 'Angular',
    'angularjs': 'Angular',
    'jest': 'Jest',
    'mocha': 'Mocha',
    'cypress': 'Cypress',
    'selenium': 'Selenium',
    'jira': 'Jira',
    'agile': 'Agile',
    'scrum': 'Scrum'
};
